### ISSUE TITLE
Genome assembly support

### ISSUE THREAD

**Issue by ghost** [your-highness/normR#13]
Hi,
I am working on the 1000 Genomes human assembly version hs37d5, which is not supported by GenomeInfoDb/normR. Are there any plans to add simple support for other assemblies (e.g., via an appropriate chromosome name/size file as additional parameter)?
I am also using EpiCSeg to process these BAM files, and this works fine - of course, I don't know how much of the code base is actually shared between these tools.
Best,
Peter

**Comment by your-highness** [comment]
Hi @mpi-pebert ,

A solution to your problem would be to hand a `data.frame` with two columns to `enrichR` which specifies chromsome names and their length, _e.g._:
```R
genome.df <- data.frame("name"=c("chr1"), "size"=c(1e6))
enrichR(treatment.file, control.file, genome.df)
```
See also https://bioconductor.org/packages/release/bioc/vignettes/normr/inst/doc/normr.html#enrichr-calling-enrichment-with-an-input-control

I hope this solves your issue.

Johannes

**Comment by ghost** [comment]
Thanks for the hint, I will give it a try.

Peter

**Comment by your-highness** [comment]
Did this solution solve your issue?

**Comment by ghost** [comment]
Yes, manually specifying the chromosome sizes seems to work fine. Thanks for your help.
